# Generated by Django 2.2.3 on 2019-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='html_content',
        ),
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_plain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
