# Generated by Django 2.2.3 on 2019-07-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190719_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_url',
            new_name='content_markdown_url',
        ),
    ]
