# Generated by Django 2.2.3 on 2019-07-19 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190719_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=31, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=31),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='page.Category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('category', 'code')},
        ),
    ]
