# Generated by Django 2.2.4 on 2019-10-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0004_add_verification_until")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_signed",
            field=models.FileField(blank=True, null=True, upload_to="file"),
        )
    ]
