# Generated by Django 2.2.4 on 2019-10-25 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("app", "0005_file_file_signed")]

    operations = [
        migrations.RemoveField(model_name="file", name="file_signed"),
        migrations.CreateModel(
            name="FileSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_submitted", models.FileField(upload_to="file")),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "INVOICE"), (1, "LETTER")], default=0
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "VALID"), (1, "DEPRECATED"), (2, "INVALID")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="app.File"
                    ),
                ),
            ],
        ),
    ]
