# Generated by Django 2.2.4 on 2019-10-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0007_filesubmission_ip")]

    operations = [
        migrations.AddField(
            model_name="filesubmission",
            name="data",
            field=models.TextField(default="{}", max_length=5000),
        )
    ]
