# Generated by Django 2.2.3 on 2019-07-10 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=31, unique=True, verbose_name='Code')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'HACKATHON')])),
            ],
        ),
    ]
