# Generated by Django 2.2.3 on 2019-07-19 14:39

from django.db import migrations, models
import django.db.models.deletion
import event.models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=31, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'HACKATHON')])),
                ('picture', versatileimagefield.fields.VersatileImageField(upload_to=event.models.path_and_rename, verbose_name='Image')),
                ('city', models.CharField(default='Stockholm', max_length=255)),
                ('country', models.CharField(default='Sweden', max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('application_status', models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'OPEN'), (2, 'CLOSED')], default=0)),
                ('application_deadline', models.DateTimeField()),
                ('custom_home', models.BooleanField(default=False)),
                ('partners', models.ManyToManyField(blank=True, null=True, related_name='partners', to='user.Company')),
                ('sponsors', models.ManyToManyField(blank=True, null=True, related_name='sponsors', to='user.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('important', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Event')),
            ],
        ),
    ]
