# Generated by Django 2.2.3 on 2019-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='partners', to='user.Company'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsors', to='user.Company'),
        ),
    ]
