# Generated by Django 2.2.3 on 2019-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190714_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_home',
            field=models.BooleanField(default=False),
        ),
    ]
