# Generated by Django 2.2.3 on 2019-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190719_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='newbie',
            field=models.BooleanField(default=False),
        ),
    ]
