# Generated by Django 2.2.3 on 2019-07-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_custom_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Stockholm', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='Sweden', max_length=255),
        ),
    ]
