# Generated by Django 2.2.3 on 2019-07-27 15:23

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_application_newbie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='newbie',
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='', upload_to=event.models.path_and_rename_resume),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='hardware',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'SAVED'), (1, 'PENDING'), (2, 'CANCELLED'), (3, 'INVITED'), (4, 'CONFIRMED'), (5, 'REJECTED'), (6, 'REMINDED'), (7, 'EXPIRED'), (8, 'DUBIOUS'), (9, 'ATTENDED')]),
        ),
    ]
