# Generated by Django 2.2.3 on 2019-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190714_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
