# Generated by Django 2.2.3 on 2019-07-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190727_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='application_status',
        ),
        migrations.AddField(
            model_name='event',
            name='application_available',
            field=models.DateTimeField(default='2019-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='diet',
            field=models.PositiveSmallIntegerField(choices=[(0, 'REGULAR'), (1, 'VEGETARIAN'), (2, 'VEGAN'), (3, 'PORK_FREE'), (4, 'GLUTEN_FREE'), (5, 'LACTOSE_FREE'), (6, 'SEAFOOD_FREE'), (7, 'OTHER')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DRAFT'), (1, 'PENDING'), (2, 'CANCELLED'), (3, 'INVITED'), (4, 'CONFIRMED'), (5, 'REJECTED'), (6, 'REMINDED'), (7, 'EXPIRED'), (8, 'DUBIOUS'), (9, 'ATTENDED')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='tshirt',
            field=models.PositiveSmallIntegerField(choices=[(10, 'XXS'), (20, 'XS'), (30, 'S'), (40, 'M'), (50, 'L'), (60, 'XL'), (70, 'XXL'), (80, 'XXXL')], default=50),
        ),
    ]
