# Generated by Django 2.2.3 on 2019-08-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0004_event_dates_public")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="faq_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="organisers_public",
            field=models.BooleanField(default=True),
        ),
    ]
