# Generated by Django 2.2.3 on 2019-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='open',
        ),
        migrations.AddField(
            model_name='event',
            name='application_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'OPEN'), (2, 'CLOSED')], default=0),
        ),
    ]
