# Generated by Django 2.2.3 on 2019-07-14 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20190714_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 16, 16, 42, 698016, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
