# Generated by Django 2.2.3 on 2019-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0008_auto_20190802_1149")]

    operations = [
        migrations.AddField(
            model_name="event", name="hackers", field=models.IntegerField(default=200)
        )
    ]
