# Generated by Django 2.2.3 on 2019-07-17 16:14

from django.db import migrations
import event.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190714_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to=event.models.path_and_rename, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
