# Generated by Django 2.2.3 on 2019-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0009_event_hackers")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="companies_open",
            field=models.BooleanField(default=True),
        )
    ]
