# Generated by Django 2.2.4 on 2019-08-09 19:30

from django.db import migrations
import event
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("event", "0011_event_subscribe_public")]

    operations = [
        migrations.RemoveField(model_name="event", name="picture"),
        migrations.AddField(
            model_name="event",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                default="", upload_to=event.models.path_and_rename, verbose_name="Logo"
            ),
            preserve_default=False,
        ),
    ]
