# Generated by Django 2.2.4 on 2019-08-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20190809_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
    ]
