# Generated by Django 2.2.4 on 2019-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0013_remove_subscriber_user")]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="events",
            field=models.ManyToManyField(to="event.Event"),
        )
    ]
