# Generated by Django 2.2.4 on 2019-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0016_invoice_code_invoice_company")]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
