# Generated by Django 2.2.4 on 2019-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("event", "0019_invoice_sent_by")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="schedule_markdown_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(name="ScheduleEvent"),
    ]
