# Generated by Django 2.2.4 on 2019-08-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_add_coding_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'HACKATHON'), (1, 'OTHER')]),
        ),
    ]
