# Generated by Django 2.2.4 on 2019-08-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("event", "0023_add_organiser_event_company_type")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="event.Team",
            ),
        )
    ]
