# Generated by Django 2.2.4 on 2019-08-25 12:53

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [("event", "0026_application_note")]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_tech",
            field=models.SmallIntegerField(validators=[event.models.valid_vote]),
        )
    ]
