# Generated by Django 2.2.4 on 2019-08-29 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0027_set_vote_to_small_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'GENERIC'), (20, 'SUBSCRIBED'), (30, 'ACCEPTED'), (40, 'LETTER'), (50, 'INVOICE'), (60, 'BILL'), (70, 'VOLUNTEERS'), (80, 'MENTORS'), (90, 'SPONSORS')], default=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=5000)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.Event')),
            ],
        ),
    ]
