# Generated by Django 2.2.4 on 2019-08-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("event", "0029_add_recipient_email")]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="event.Event",
            ),
        )
    ]
