# Generated by Django 2.2.4 on 2019-09-10 10:43

from django.db import migrations
import event.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("event", "0032_enable_skip_on_vote")]

    operations = [
        migrations.AddField(
            model_name="companyevent",
            name="current_logo",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=event.models.path_and_rename_company,
                verbose_name="Image",
            ),
        )
    ]
