# Generated by Django 2.2.4 on 2019-09-28 10:45

from django.db import migrations
import event.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_add_organizers_volunteers_mentors_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_clean',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=event.models.path_and_rename, verbose_name='Clean logo'),
        ),
    ]
