# Generated by Django 2.2.4 on 2019-09-29 09:45

from django.db import migrations
import event.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_event_logo_white_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_white',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=event.models.path_and_rename, verbose_name='White logo'),
        ),
    ]
