# Generated by Django 2.2.4 on 2019-10-19 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_add_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'VISA'), (1, 'UNDERAGE')], default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_seny_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
