# Generated by Django 2.2.4 on 2019-10-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_change_attachment_for_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.File'),
        ),
        migrations.RemoveField(model_name="letter", name="letter"),
        migrations.AddField(
            model_name='letter',
            name='letter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.File'),
        ),
    ]
