# Generated by Django 2.2.4 on 2019-10-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0041_change_letter_for_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.File'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
