# Generated by Django 2.2.3 on 2019-07-10 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=31, unique=True)),
            ],
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=31, unique=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "ADMIN"),
                            (1, "DIRECTOR"),
                            (2, "DESIGN"),
                            (3, "FINANCE"),
                            (4, "FUNDRAISING"),
                            (5, "HACKERXPERIENCE"),
                            (6, "LOGISTICS"),
                            (7, "MARKETING"),
                            (8, "PHOTOGRAPHY"),
                            (9, "STAFF"),
                            (10, "WEBDEV"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255, verbose_name="First name")),
                ("surname", models.CharField(max_length=255, verbose_name="Last name")),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "PARTICIPANT"),
                            (1, "ORGANISER"),
                            (2, "SPONSOR"),
                            (3, "MEDIA"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "sex",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "NONE"), (1, "FEMALE"), (2, "MALE")],
                        default=user.enums.SexType(0),
                    ),
                ),
                ("age", models.IntegerField(default=18)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.Company",
                    ),
                ),
                ("departments", models.ManyToManyField(to="user.Department")),
            ],
            options={"abstract": False},
        ),
    ]
