# Generated by Django 2.2.3 on 2019-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190711_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PARTICIPANT'), (1, 'ORGANISER'), (2, 'MENTOR'), (3, 'SPONSOR'), (4, 'RECRUITER'), (5, 'MEDIA')], default=0),
        ),
    ]
