# Generated by Django 2.2.3 on 2019-08-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_event_dates_public"),
        ("user", "0002_user_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="events",
            field=models.ManyToManyField(blank=True, to="event.Event"),
        )
    ]
