# Generated by Django 2.2.3 on 2019-08-02 08:46

from django.db import migrations, models
import user.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("user", "0003_user_events")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=versatileimagefield.fields.VersatileImageField(
                default="",
                upload_to=user.models.path_and_rename_company,
                verbose_name="Image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
