# Generated by Django 2.2.4 on 2019-08-10 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190802_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_expiration',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 7, 42, 33, 918635, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_key',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
