# Generated by Django 2.2.4 on 2019-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0005_add_verification")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="address_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="organisation_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="organisation_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="postcode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
