# Generated by Django 2.2.4 on 2019-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0007_alter_department_names")]

    operations = [
        migrations.AddField(
            model_name="user", name="is_active", field=models.BooleanField(default=True)
        )
    ]
