# Generated by Django 2.2.4 on 2019-10-18 21:51

from django.db import migrations, models
import user.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'ID'), (1, 'PASSPORT')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=user.models.path_and_rename_signature, verbose_name='Image'),
        ),
    ]
