# Generated by Django 2.2.4 on 2019-10-20 13:17

from django.db import migrations
import user.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [("user", "0009_add_id_information")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="signature",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to=user.models.path_and_rename_signature,
                verbose_name="Signature",
            ),
        )
    ]
